## Audio based Speaker identification using embeddings 

In [1]:
from pyannote.audio import Model
from pyannote.audio import Inference
from scipy.spatial.distance import cdist
import os

/home/easgrad/ninadnar/miniconda3/envs/bio1/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = Model.from_pretrained("pyannote/embedding", use_auth_token="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")
inference = Inference(model, window="whole")

Lightning automatically upgraded your loaded checkpoint from v1.2.7 to v2.0.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../.cache/torch/pyannote/models--pyannote--embedding/snapshots/20b2db779562a3141f5eadd34a0232dbcd56d620/pytorch_model.bin`
Lightning automatically upgraded your loaded checkpoint from v1.2.7 to v2.0.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../.cache/torch/pyannote/models--pyannote--embedding/snapshots/20b2db779562a3141f5eadd34a0232dbcd56d620/pytorch_model.bin`


Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.8.1+cu102, yours is 2.0.1. Bad things might happen unless you revert torch to 1.x.
Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.8.1+cu102, yours is 2.0.1. Bad things might happen unless you revert torch to 1.x.


# Embedding matching 
In VIDTIMIT dataset, sa1 file includes audio of 43 people saying following sentence 
"She had your dark suitin greasy wash water all year"

Test code for calculating embedding of same speaker

In [36]:
path_1 = "VIDTIMIT/fadg0/audio/sa1.wav"
path_2 = "VIDTIMIT/mdab0/audio/sa2.wav"

embedding1 = inference(path_1)
embedding2 = inference(path_2)

embedding1 = embedding1.reshape(1,512)
embedding2 = embedding2.reshape(1,512)

distance = cdist(embedding1, embedding2, metric="cosine")
distance

array([[0.91288073]])

In [3]:
import subprocess

def convert_m4a_to_wav(input_file, output_file):
    command = ['ffmpeg', '-i', input_file, '-acodec', 'pcm_s16le', '-ar', '44100', '-ac', '2', output_file]
    subprocess.call(command)

# Usage example
input_file = 'dataset/tbd/test2.m4a'
output_file = 'dataset/tbd/n2.wav'
convert_m4a_to_wav(input_file, output_file)

input_file = 'dataset/tbd/test1.m4a'
output_file = 'dataset/tbd/n1.wav'
convert_m4a_to_wav(input_file, output_file)

input_file = 'dataset/tbd/akhil1.m4a'
output_file = 'dataset/tbd/a1.wav'
convert_m4a_to_wav(input_file, output_file)

input_file = 'dataset/tbd/akhil1.m4a'
output_file = 'dataset/tbd/a2.wav'
convert_m4a_to_wav(input_file, output_file)

input_file = 'dataset/tbd/vinnop1.m4a'
output_file = 'dataset/tbd/v1.wav'
convert_m4a_to_wav(input_file, output_file)

input_file = 'dataset/tbd/vinoop2.m4a'
output_file = 'dataset/tbd/v2.wav'
convert_m4a_to_wav(input_file, output_file)

ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
  configuration: --prefix=/opt/conda/conda-bld/ffmpeg_1597178665428/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh --cc=/opt/conda/conda-bld/ffmpeg_1597178665428/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-pic --enable-pthreads --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libsw

# Save embeddings

In [29]:
# Example usage
directory_path = 'dataset/dat/'
embedding_dict_1 = {}
embedding_dict_2 = {}

for root, dirs, files in os.walk(directory_path):
        for file_name in files:
            if "1" in file_name and ".wav" in file_name:
                file_path = os.path.join(root, file_name)
                embedding1 = inference(file_path)
                embedding1 = embedding1.reshape(1,512)
                embedding_dict_1[file_name] = embedding1
                
for root, dirs, files in os.walk(directory_path):
        for file_name in files:
            if "2" in file_name and ".wav" in file_name:
                file_path = os.path.join(root, file_name)
                embedding1 = inference(file_path)
                embedding1 = embedding1.reshape(1,512)
                embedding_dict_2[file_name] = embedding1

# Test

In [42]:
for key , emb in embedding_dict_1.items():
    min_val = 100
    match = None
    
    print(f'\nFor {key}')
    print("----------- \n")
    for key2, emb2 in embedding_dict_2.items():
        distance = cdist(emb, emb2, metric="cosine")
        if min_val > float(distance):
            match = key2
            min_val = distance
        print(f'Distance with {key2} is \t\t {distance}')
        
    print (f'\n{key} -> {match} : \t\t {min_val}')
    


For v1.wav
----------- 

Distance with kshitij_2.wav is 		 [[0.83540551]]
Distance with v2.wav is 		 [[0.45263119]]
Distance with ninad_2.wav is 		 [[0.80595515]]
Distance with rahul_2.wav is 		 [[0.84465358]]
Distance with a2.wav is 		 [[0.83884068]]
Distance with sougato_2.wav is 		 [[0.86125886]]
Distance with smit_2.wav is 		 [[0.84391713]]
Distance with steven_2.wav is 		 [[0.89682833]]

v1.wav -> v2.wav : 		 [[0.45263119]]

For kshitij_1.wav
----------- 

Distance with kshitij_2.wav is 		 [[0.60268838]]
Distance with v2.wav is 		 [[0.75050098]]
Distance with ninad_2.wav is 		 [[0.78902336]]
Distance with rahul_2.wav is 		 [[0.93362352]]
Distance with a2.wav is 		 [[0.8955035]]
Distance with sougato_2.wav is 		 [[0.8104183]]
Distance with smit_2.wav is 		 [[0.88873408]]
Distance with steven_2.wav is 		 [[0.82589953]]

kshitij_1.wav -> kshitij_2.wav : 		 [[0.60268838]]

For smit_1.wav
----------- 

Distance with kshitij_2.wav is 		 [[0.85314586]]
Distance with v2.wav is 		 [[0.816

In [32]:

distance = cdist(embedding_dict_1["v1.wav"], embedding_dict_2["v2.wav"], metric="cosine")
distance

array([[0.45263119]])

In [27]:
path_1 = "dataset/dat/v1.wav"
path_2 = "dataset/dat/v2.wav"

embedding1 = inference(path_1)
embedding2 = inference(path_2)

embedding1 = embedding1.reshape(1,512)
embedding2 = embedding2.reshape(1,512)

distance = cdist(embedding1, embedding2, metric="cosine")
distance

array([[0.45263119]])

Store Embeddings of all voices based on test voice

In [37]:
directory = 'VIDTIMIT'
labels = [name for name in os.listdir(directory) if os.path.isdir(os.path.join(directory, name))]
embeddings = {}

for label in labels:
    audio_path = f"{directory}/{label}/audio/sa1.wav"
    embedding = inference(audio_path).reshape(1,512)
    embeddings[label] = embedding

In [50]:
correct_detection_count = 0
for label in labels:
    curr_emd = inference(f"{directory}/{label}/audio/sa2.wav").reshape(1,512)
    min_dist = 10
    match_label = -1
    for test_label, test_embd in embeddings.items():
        distance = cdist(curr_emd, test_embd, metric="cosine")
        if distance <= min_dist :
            match_label = test_label
            min_dist = distance
    print(label ," -> ", match_label, " : cosine dist :" , min_dist)
    if match_label == label:
        correct_detection_count += 1
accuracy = correct_detection_count/ 43
print("-"*50)
print("-"*50)
print("Accuracy is :" , accuracy*100 , "%" )  
print("-"*50)
print("-"*50)    

fgjd0  ->  fgjd0  : cosine dist : [[0.55651954]]
mtas1  ->  mtas1  : cosine dist : [[0.54014845]]
fram1  ->  fram1  : cosine dist : [[0.45948952]]
fcft0  ->  fcft0  : cosine dist : [[0.42452628]]
mjar0  ->  mjar0  : cosine dist : [[0.43316354]]
mstk0  ->  mstk0  : cosine dist : [[0.52967133]]
fjem0  ->  fjem0  : cosine dist : [[0.51770773]]
mabw0  ->  mabw0  : cosine dist : [[0.50771203]]
mccs0  ->  mccs0  : cosine dist : [[0.34471623]]
fdrd1  ->  fdrd1  : cosine dist : [[0.65763457]]
fjwb0  ->  fjwb0  : cosine dist : [[0.45850801]]
mbdg0  ->  mbdg0  : cosine dist : [[0.43197923]]
mdld0  ->  mdld0  : cosine dist : [[0.44568772]]
fjre0  ->  fjre0  : cosine dist : [[0.46684462]]
mrgg0  ->  mrgg0  : cosine dist : [[0.39163365]]
fadg0  ->  fadg0  : cosine dist : [[0.52232371]]
fdms0  ->  fdms0  : cosine dist : [[0.49582067]]
mrjo0  ->  mrjo0  : cosine dist : [[0.64158947]]
mmdm2  ->  mmdm2  : cosine dist : [[0.50485464]]
fcrh0  ->  fcrh0  : cosine dist : [[0.50851035]]
fedw0  ->  fedw0  : 

# Observation

Embedding extracted by pyannote are good enough to do speaker recognition and as can be seen accuracy is 100%